### ISSUE TITLE
Local search doesn't show the page title

### ISSUE THREAD

**Issue by shimonacarvalho** [trussworks/Engineering-Playbook#268]
The search plugin doesn't show the name of the page, next to headings, which can be useful to figure out where that heading is located. It used to show this, in previous versions, and could just be a setting somewhere. 

![image](https://user-images.githubusercontent.com/40670806/164567464-bedcad76-921d-4a70-a310-d5ed8aa30663.png)

**Comment by kleinschmidtj** [comment]
This appears to be a bug with the [docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local) package. I noticed that the search index just contains empty strings for each `pageTitle` field. I've highlighted one entry where the "Links" subheader shows up:

<img width="991" alt="Screen Shot 2022-10-03 at 12 27 42 PM" src="https://user-images.githubusercontent.com/57681819/193661652-55c14d52-7b59-452c-b186-ff30600a6009.png">

To get this feature to work (and for the `pageTitle` field to show up in the index), you can add the title via front matter. 

<img width="689" alt="Screen Shot 2022-10-03 at 12 29 23 PM" src="https://user-images.githubusercontent.com/57681819/193662185-e0f69985-265e-41d2-9f71-97509a15e3ea.png">

But since that would be such a pain for all of these docs, I went ahead and filed a bug [here](https://github.com/cmfcmf/docusaurus-search-local/issues/146).

**Comment by rogeruiz** [comment]
This has been fixed in the work done in #311.

<img width="913" alt="Captura de pantalla 2023-02-03 a la(s) 5 49 56 p m" src="https://user-images.githubusercontent.com/706004/216725760-c8c7f6a0-cfd9-453d-9190-38979f828569.png">
